Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEB.Data;
using PWEB.Models;

namespace PWEB.Controllers
{
    public class EmpresasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Utilizador> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public EmpresasController(ApplicationDbContext context
            , UserManager<Utilizador> userManager
            , RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Empresas
        public async Task<IActionResult> Index()
        {
              return View(await _context.Empresas.ToListAsync());
        }

        // GET: Empresas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Empresas == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empresa == null)
            {
                return NotFound();
            }

            return View(empresa);
        }

        // GET: Empresas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empresas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Disponivel,Eliminar")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                //inicializar 

                empresa.Empregados = new List<Utilizador>();
                empresa.Veiculos= new List<Veiculo>();
                empresa.Reservas = new List<Reserva>();
                empresa.Avaliacoes = new List<Avaliacao>();
                empresa.Subscricoes = new List<Subscricao>();

                // criar o gestor

                var defaultUser = new Utilizador
                {
                    UserName = "gestor"+empresa.Nome + "@localhost.com",
                    Email = "gestor" + empresa.Nome + "@localhost.com",
                    EmailConfirmed = true,
                    PhoneNumberConfirmed = true,
                    Nome = "Gestor",
                    Apelido = "Gestor",
                    NIF = 0,
                    Morada = "",
                    DataNascimento = new DateTime(),
                    NumeroCartaoMultibanco = 0,
                    ValidadeCartaoMultibanco = new DateTime(),
                    CvdCartaoMultibanco = 0,
                    Disponivel = true

                };
                //Adicionar o gestor a empresa

                empresa.Empregados.Add(defaultUser);

                // adicionar pass e role de gestor
                var user = await _userManager.FindByEmailAsync(defaultUser.Email);
                if (user == null)
                {
                    await _userManager.CreateAsync(defaultUser, "Gestor10.");
                    await _userManager.AddToRoleAsync(defaultUser,
                    Roles.Gestor.ToString());
                }

                _context.Add(empresa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empresa);
        }

        // GET: Empresas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Empresas == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresas.FindAsync(id);
            if (empresa == null)
            {
                return NotFound();
            }
            return View(empresa);
        }

        // POST: Empresas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Disponivel,Eliminar")] Empresa empresa)
        {
            if (id != empresa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empresa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpresaExists(empresa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empresa);
        }

        // GET: Empresas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Empresas == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empresa == null)
            {
                return NotFound();
            }

            return View(empresa);
        }

        // POST: Empresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Empresas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Empresas'  is null.");
            }
            var empresa = await _context.Empresas.FindAsync(id);
            if (empresa != null)
            {
                if (empresa.Veiculos == null )
                {
                    // remover os funcionarios antes de remover a empresa 
                    var utizadores =  _userManager.Users.Where(u => u.EmpresaId == id);
                    foreach (var item in utizadores)
                    {

                        _context.Users.Remove(item);
                    }
                       
                    _context.Empresas.Remove(empresa);
 
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                }
                // nao se pode remover empresa se esta possui veiculos 
                if (empresa.Veiculos.Count() != 0)
                {
                    return Problem("Nao e possivel remover empresa, pois esta possui veiculos. ");
                }
                _context.Empresas.Remove(empresa);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpresaExists(int id)
        {
          return _context.Empresas.Any(e => e.Id == id);
        }
    }
}

Controllers/EntregasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEB.Data;
using PWEB.Models;
using PWEB.ViewModel;

namespace PWEB.Controllers
{
    public class EntregasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Utilizador> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public EntregasController(ApplicationDbContext context
            , UserManager<Utilizador> userManager
            , RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Entregas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Entregas.Include(e => e.Empregado);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Entregas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Entregas == null)
            {
                return NotFound();
            }

            var entrega = await _context.Entregas
                .Include(e => e.Empregado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entrega == null)
            {
                return NotFound();
            }

            return View(entrega);
        }

        // GET: Entregas/Create
        public async Task<IActionResult> Create(int? id ,string rId, string? fId)
        {
            if ( _context.Reserva == null)
            {
                return NotFound();
            }

            
            var user = await _userManager.GetUserAsync(User);
            var reserva = await _context.Reserva
                .Include(r => r.EmpregadoCliente)
                .FirstOrDefaultAsync(r => r.Id == Int32.Parse(rId));

            if (fId == null)
            {         
                fId = user.Id;
            }

            // Verificar se a reserga ja tem uma entrega
            if (reserva.EntregaId != null)
            {
                ErroViewModel e = new ErroViewModel();
                e.Mensagem = "A reserva ja esta entrege";
                e.Controller = "Reservas";

                return View("Erro", e);
            }

            // verificar se a reserva ja foi confirmada 
            if (reserva.Confirmado != true)
            {
                ErroViewModel e = new ErroViewModel();
                e.Mensagem = "A reserva ainda não foi confirmada";
                e.Controller = "Reservas";

                return View("Erro", e);
            }

            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email",fId);
            ViewData["Reserva"] = rId;

            return View();
        }

        // POST: Entregas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int rId,[Bind("Id,Kilometros,Danos,Observaçoes,EmpregadoId")] Entrega entrega)
        {

            ModelState.Remove(nameof(entrega.Empregado));
            if (ModelState.IsValid)
            {

                // primeiro adicionar entrega a BD e actualizar
                _context.Add(entrega);
               await _context.SaveChangesAsync();

                // adicionar a entrega a reseverva
                if (_context.Reserva == null)
                {
                    return NotFound();
                }
                // actualizar a reserva com a entrega e adicionar a BD
                var r = await _context.Reserva
                .Include(r => r.Avaliacao).
                Include(r => r.Entrega).
                Include(r => r.Recolha).
                Include(r => r.Veiculo).
                Include(r => r.empresa).
                Include(r => r.EmpregadoCliente).
                FirstOrDefaultAsync(r => r.Id == rId);
                r.EntregaId = entrega.Id;

                _context.Update(r);

                // por fin guardar as akteraçoes na BD
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email", entrega.EmpregadoId);
            ViewData["Reserva"] = rId;
            return View(entrega);
        }

        // GET: Entregas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Entregas == null)
            {
                return NotFound();
            }

            var entrega = await _context.Entregas.FindAsync(id);
            if (entrega == null)
            {
                return NotFound();
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email", entrega.EmpregadoId);
            return View(entrega);
        }

        // POST: Entregas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Kilometros,Danos,Observaçoes,EmpregadoId")] Entrega entrega)
        {
            if (id != entrega.Id)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(entrega.Empregado));
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entrega);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EntregaExists(entrega.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email", entrega.EmpregadoId);
            return View(entrega);
        }

        // GET: Entregas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Entregas == null)
            {
                return NotFound();
            }

            var entrega = await _context.Entregas
                .Include(e => e.Empregado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entrega == null)
            {
                return NotFound();
            }

            return View(entrega);
        }

        // POST: Entregas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Entregas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Entregas'  is null.");
            }
            var entrega = await _context.Entregas.FindAsync(id);
            if (entrega != null)
            {
                _context.Entregas.Remove(entrega);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EntregaExists(int id)
        {
          return _context.Entregas.Any(e => e.Id == id);
        }
    }
}

Views/Shared/Erro.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



@model PWEB.ViewModel.ErroViewModel;


@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">@Model.Mensagem</h2>

<div>
    <a asp-controller="@Model.Controller" asp-action="Index">Back</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PWEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rental4You</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empresas" asp-action="Index">Empresas</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" data-bs-toggle="dropdown" aria-expanded="false">Veiculos</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item " asp-area="" asp-controller="Veiculos" asp-action="Index">Veiculos</a></li>
                                <li><a class="dropdown-item " asp-area="" asp-controller="TipoVeiculos" asp-action="Index">Categorias</a></li>                       
                            </ul>   
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" data-bs-toggle="dropdown" aria-expanded="false">Utilizadores</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Utilizadores" asp-action="Index">Utilizadores</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Avaliacaos" asp-action="Index">Avaliacoes</a></li>                       
                            </ul>   
                        </li>
                        <li class="nav-item">
                            
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" data-bs-toggle="dropdown" aria-expanded="false">Reservas</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item " asp-area="" asp-controller="Reservas" asp-action="Index">Reservas</a></li>
                                <li><a class="dropdown-item " asp-area="" asp-controller="Reservas" asp-action="Criar">Criar</a></li>
                                <li><a class="dropdown-item " asp-area="" asp-controller="Reservas" asp-action="Historico">Historico</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Entregas" asp-action="Index">Entregas</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" data-bs-toggle="dropdown" aria-expanded="false">Recolhas</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Recolhas" asp-action="Index">Recolhas</a></li>
                                <li><a class="dropdown-item " asp-area="" asp-controller="Imagems" asp-action="Index">Imagens</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PWEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>