Models/Reserva.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace PWEB.Models
{
    public class Reserva
    {
       public int Id { get; set; }
       public DateTime DataDeLevantaneto { get; set; }
       public DateTime DataDeEntrega { get; set; }
       public bool?  Confirmado { get; set; } = false;

       public DateTime? Eliminar { get; set; }

       public int EmpresaId { get; set; }  // relacao 1-N
       public Empresa empresa{ get; set; }

       public int VeiculoId { get; set; }  // relacao 1-N
       public Veiculo Veiculo { get; set; }

       public ICollection<Utilizador> EmpregadoCliente { get; set; } // relacao M-N 

       public int? EntregaId { get; set; }
       public Entrega? Entrega { get; set; }  // 1-to-1 Relacao

       public int? RecolhaId { get; set; }
       public Recolha? Recolha { get; set; }  // 1-to-1 Relacao

       public int? AvaliacaoId { get; set; }
       public Avaliacao? Avaliacao { get; set; } // 1-to-1 Relacao

    }
}

Controllers/EntregasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEB.Data;
using PWEB.Models;
using PWEB.ViewModel;

namespace PWEB.Controllers
{
    public class EntregasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Utilizador> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public EntregasController(ApplicationDbContext context
            , UserManager<Utilizador> userManager
            , RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Entregas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Entregas.Include(e => e.Empregado);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Entregas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Entregas == null)
            {
                return NotFound();
            }

            var entrega = await _context.Entregas
                .Include(e => e.Empregado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entrega == null)
            {
                return NotFound();
            }

            return View(entrega);
        }

        // GET: Entregas/Create
        public async Task<IActionResult> Create(int? id ,string rId, string? fId)
        {
            if ( _context.Reserva == null)
            {
                return NotFound();
            }

            
            var user = await _userManager.GetUserAsync(User);
            var reserva = await _context.Reserva
                .Include(r => r.EmpregadoCliente)
                .FirstOrDefaultAsync(r => r.Id == Int32.Parse(rId));

            if (fId == null)
            {         
                fId = user.Id;
            }

            // Verificar se a reserga ja tem uma entrega
            if (reserva.EntregaId != null)
            {
                ErroViewModel e = new ErroViewModel();
                e.Mensagem = "A reserva ja esta entrege";
                e.Controller = "Reservas";

                return View("Erro", e);
            }

            // verificar se a reserva ja foi confirmada 
            if (reserva.Confirmado != true)
            {
                ErroViewModel e = new ErroViewModel();
                e.Mensagem = "A reserva ainda não foi confirmada";
                e.Controller = "Reservas";

                return View("Erro", e);
            }

            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email",fId);
            ViewData["Reserva"] = rId;

            return View();
        }

        // POST: Entregas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int rId,[Bind("Id,Kilometros,Danos,Observaçoes,EmpregadoId")] Entrega entrega)
        {

            ModelState.Remove(nameof(entrega.Empregado));
            if (ModelState.IsValid)
            {

                // primeiro adicionar entrega a BD e actualizar
                _context.Add(entrega);
               await _context.SaveChangesAsync();

                // adicionar a entrega a reseverva
                if (_context.Reserva == null)
                {
                    return NotFound();
                }
                // actualizar a reserva com a entrega e adicionar a BD
                var r = await _context.Reserva
                .Include(r => r.Avaliacao).
                Include(r => r.Entrega).
                Include(r => r.Recolha).
                Include(r => r.Veiculo).
                Include(r => r.empresa).
                Include(r => r.EmpregadoCliente).
                FirstOrDefaultAsync(r => r.Id == rId);
                r.EntregaId = entrega.Id;

                _context.Update(r);

                // por fin guardar as akteraçoes na BD
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email", entrega.EmpregadoId);
            ViewData["Reserva"] = rId;
            return View(entrega);
        }

        // GET: Entregas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Entregas == null)
            {
                return NotFound();
            }

            var entrega = await _context.Entregas.FindAsync(id);
            if (entrega == null)
            {
                return NotFound();
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email", entrega.EmpregadoId);
            return View(entrega);
        }

        // POST: Entregas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Kilometros,Danos,Observaçoes,EmpregadoId")] Entrega entrega)
        {
            if (id != entrega.Id)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(entrega.Empregado));
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entrega);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EntregaExists(entrega.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email", entrega.EmpregadoId);
            return View(entrega);
        }

        // GET: Entregas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Entregas == null)
            {
                return NotFound();
            }

            var entrega = await _context.Entregas
                .Include(e => e.Empregado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entrega == null)
            {
                return NotFound();
            }

            return View(entrega);
        }

        // POST: Entregas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Entregas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Entregas'  is null.");
            }
            var entrega = await _context.Entregas.FindAsync(id);
            if (entrega != null)
            {
                _context.Entregas.Remove(entrega);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EntregaExists(int id)
        {
          return _context.Entregas.Any(e => e.Id == id);
        }
    }
}

Controllers/RecolhasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEB.Data;
using PWEB.Models;
using PWEB.ViewModel;

namespace PWEB.Controllers
{
    public class RecolhasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Utilizador> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public RecolhasController(ApplicationDbContext context
            , UserManager<Utilizador> userManager
            , RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Recolhas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Recolhas.Include(r => r.Empregado);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Recolhas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Recolhas == null)
            {
                return NotFound();
            }

            var recolha = await _context.Recolhas
                .Include(r => r.Empregado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recolha == null)
            {
                return NotFound();
            }

            return View(recolha);
        }

        // GET: Recolhas/Create
        public async Task<IActionResult> Create(int? id, string rId, string? fId)
        {

            if (_context.Reserva == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            var reserva = await _context.Reserva
                .Include(r => r.EmpregadoCliente)
                .FirstOrDefaultAsync(r => r.Id == Int32.Parse(rId));

            if (fId == null)
            {
                fId = user.Id;
            }

            // Verificar se a reserga ja tem uma recolha
            if (reserva.RecolhaId != null)
            {
                ErroViewModel e = new ErroViewModel();
                e.Mensagem = "A reserva ja foi recolhida";
                e.Controller = "Reservas";

                return View("Erro", e);
            }

            // Verificar se a reserga ja tem uma entrega
            if (reserva.EntregaId == null)
            {
                ErroViewModel e = new ErroViewModel();
                e.Mensagem = "Primeiro tem de ser realizada a entrega";
                e.Controller = "Reservas";

                return View("Erro", e);
            }

            // verificar se a reserva ja foi confirmada 
            if (reserva.Confirmado != true)
            {
                ErroViewModel e = new ErroViewModel();
                e.Mensagem = "A reserva ainda não foi confirmada";
                e.Controller = "Reservas";

                return View("Erro", e);
            }

            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email", fId);
            ViewData["Reserva"] = rId;

            return View();
        }

        // POST: Recolhas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int rId, [Bind("Id,Kilometros,Danos,Observaçoes,EmpregadoId")] Recolha recolha)
        {
            ModelState.Remove(nameof(recolha.Empregado));
            if (ModelState.IsValid)
            {

                // primeiro adicionar recolha a BD e actualizar
                _context.Add(recolha);
                await _context.SaveChangesAsync();

                // adicionar a recolha a reseverva
                if (_context.Reserva == null)
                {
                    return NotFound();
                }

                // actualizar a reserva com a recolha e adicionar a BD
                var r = await _context.Reserva
                .Include(r => r.Avaliacao).
                Include(r => r.Entrega).
                Include(r => r.Recolha).
                Include(r => r.Veiculo).
                Include(r => r.empresa).
                Include(r => r.EmpregadoCliente).
                FirstOrDefaultAsync(r => r.Id == rId);
                r.RecolhaId = recolha.Id;

                _context.Update(r);

                // por fin guardar as akteraçoes na BD
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Email", recolha.EmpregadoId);
            ViewData["Reserva"] = rId;
            return View(recolha);
        }

        // GET: Recolhas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Recolhas == null)
            {
                return NotFound();
            }

            var recolha = await _context.Recolhas.FindAsync(id);
            if (recolha == null)
            {
                return NotFound();
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Id", recolha.EmpregadoId);
            return View(recolha);
        }

        // POST: Recolhas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Kilometros,Danos,Observaçoes,EmpregadoId")] Recolha recolha)
        {
            if (id != recolha.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recolha);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecolhaExists(recolha.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpregadoId"] = new SelectList(_context.Users, "Id", "Id", recolha.EmpregadoId);
            return View(recolha);
        }

        // GET: Recolhas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Recolhas == null)
            {
                return NotFound();
            }

            var recolha = await _context.Recolhas
                .Include(r => r.Empregado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recolha == null)
            {
                return NotFound();
            }

            return View(recolha);
        }

        // POST: Recolhas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Recolhas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Recolhas'  is null.");
            }
            var recolha = await _context.Recolhas.FindAsync(id);
            if (recolha != null)
            {
                _context.Recolhas.Remove(recolha);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecolhaExists(int id)
        {
          return _context.Recolhas.Any(e => e.Id == id);
        }
    }
}

Views/Reservas/Aceitar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model PWEB.Models.Reserva


<h4>Aceitar Reserva</h4>
<hr />
<div class="row">

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeLevantaneto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDeLevantaneto)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeEntrega)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDeEntrega)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Eliminar)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Eliminar)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Veiculo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Veiculo.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entrega)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entrega.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Recolha)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Recolha.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Avaliacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.empresa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.empresa.Nome)
        </dd>
    </dl>
    <div class="col-md-4">
        <form asp-action="Aceitar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DataDeLevantaneto" />
            <input type="hidden" asp-for="DataDeEntrega" />
            <input type="hidden" asp-for="Eliminar" />
            <input type="hidden" asp-for="VeiculoId" />
            <input type="hidden" asp-for="EmpresaId" />
            <input type="hidden" asp-for="EntregaId" />
            <input type="hidden" asp-for="RecolhaId" />
            <input type="hidden" asp-for="AvaliacaoId" />

            <div class="form-group">
                <input type="submit" value="Aceitar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/Reservas/Create.cshtml
@model PWEB.Models.Reserva

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Reserva</h4>
<hr />


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EntregaId"/>
            <input type="hidden" asp-for="RecolhaId"/>
            <input type="hidden" asp-for="AvaliacaoId"/>
            

            <div class="form-group">
                <label asp-for="DataDeLevantaneto" class="control-label"></label>
                <input asp-for="DataDeLevantaneto" class="form-control" />
                <span asp-validation-for="DataDeLevantaneto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDeEntrega" class="control-label"></label>
                <input asp-for="DataDeEntrega" class="form-control" />
                <span asp-validation-for="DataDeEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Eliminar" class="control-label"></label>
                <input asp-for="Eliminar" class="form-control" />
                <span asp-validation-for="Eliminar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VeiculoId" class="control-label"></label>
                <select asp-for="VeiculoId" class="form-control" asp-items="ViewBag.VeiculoId"></select>
                <span asp-validation-for="VeiculoId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>

        <div class="row">
            <a asp-action="Index">Back to List</a>
            <a asp-action="Criar">Back to Reservar</a>
        </div>
    </div>
</div>
 



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reservas/Criar.cshtml
@model IEnumerable<PWEB.Models.Veiculo>

@{
    ViewData["Title"] = "Index";
}

<h1>Primeiro selecione um veiculo</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lugares)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MudançasManuais)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PreçoPorHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Localização)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Disponivel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Eliminar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.empresa)
            </th>
            <th>
                @Html.Encode("Classificacao")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lugares)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MudançasManuais)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PreçoPorHora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Localização)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Disponivel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Eliminar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.empresa.Nome)
                </td>
                <td>
                    @{
                        double? r=0.0;
                        int c = 0;
                        foreach (Empresa e in ViewBag.es)
                        {
                            if (e.Id == item.EmpresaId)
                            {
                                foreach (Reserva re in ViewBag.rs)
                                {
                                    if (re.EmpresaId == e.Id)
                                    {
                                        if (re.Avaliacao == null)
                                        {
                                            continue;
                                        }
                                        r += re.Avaliacao.Valor;
                                        c++;
                                    }
                                }
                            }
                        }
                        var result = r / c;
                        if (result>0)
                        {
                            @(result)
                        }else{ @(0) }
                    }
                </td>
                <td>
                    <a asp-controller="Reservas" asp-action="Create">Reservar</a> |
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Reservas/Delete.cshtml
@model PWEB.Models.Reserva

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeLevantaneto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataDeLevantaneto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeEntrega)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataDeEntrega)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Eliminar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Eliminar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Veiculo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Veiculo.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Entrega)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Entrega.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recolha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recolha.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avaliacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Reservas/Index.cshtml
@model IEnumerable<PWEB.Models.Reserva>

@{
    ViewData["Title"] = "Gestão de Reservas";
}

<h1>Gestão de Reservas</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Confirmado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataDeLevantaneto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataDeEntrega)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Eliminar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Veiculo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Entrega)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recolha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Avaliacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.empresa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Confirmado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataDeLevantaneto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataDeEntrega)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Eliminar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Veiculo.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Entrega.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recolha.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Avaliacao.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.empresa.Nome)
            </td>
            <td>
                <a asp-action="Aceitar" asp-route-id="@item.Id">Aceitar</a> |
                <a asp-controller="Entregas" asp-action="Create" asp-route-rId="@item.Id">Entrega</a> |
                <a asp-controller="Recolhas" asp-action="Create" asp-route-rId="@item.Id">Recolha</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>